--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.13.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2016/9/18 星期日 16:16:48
-- Server version: 5.7.13-log
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
drop database if EXISTS changhongmyblog;
create database changhongmyblog;
USE changhongmyblog;

--
-- Definition for table blog
--
DROP TABLE IF EXISTS blog;
CREATE TABLE blog (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  data TEXT DEFAULT NULL,
  createtime DATETIME NOT NULL,
  updatetime DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table image
--
DROP TABLE IF EXISTS image;
CREATE TABLE image (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  url VARCHAR(255) DEFAULT NULL,
  data BLOB DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table user
--
DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) BINARY CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  password VARCHAR(255) NOT NULL,
  imageurl VARCHAR(255) DEFAULT NULL,
  logintime DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX name (name)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '4'
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table blog
--

-- Table changhongmyblog.blog does not contain any data (it is empty)

-- 
-- Dumping data for table image
--

-- Table changhongmyblog.image does not contain any data (it is empty)

-- 
-- Dumping data for table user
--

-- Table changhongmyblog.user does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;