--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.13.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2016/9/18 星期日 15:43:43
-- Server version: 5.7.13-log
-- Client version: 4.1
--


--
-- Definition for database changhongmyblog
--
--DROP DATABASE IF EXISTS changhongmyblog;
CREATE database IF NOT EXISTS changhongmyblog
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE changhongmyblog;

--
-- Definition for table blog
--
CREATE TABLE IF NOT EXISTS blog (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  title varchar(255) NOT NULL,
  data text DEFAULT NULL,
  createtime datetime NOT NULL,
  updatetime datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
;

--
-- Definition for table image
--
CREATE TABLE IF NOT EXISTS image (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  url varchar(255) DEFAULT NULL,
  data blob DEFAULT NULL,
  PRIMARY KEY (id)
)
;

--
-- Definition for table user
--
CREATE TABLE IF NOT EXISTS user (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  name varchar(50) binary CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  password varchar(255) NOT NULL,
  imageurl varchar(255) DEFAULT NULL,
  logintime datetime NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX name (name)
)
;

-- 
-- Dumping data for table blog
--

-- Table changhongmyblog.blog does not contain any data (it is empty)

-- 
-- Dumping data for table image
--

-- Table changhongmyblog.image does not contain any data (it is empty)

-- 
-- Dumping data for table user
--

-- Table changhongmyblog.user does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;